### ISSUE TITLE
Rolltable for only "Currency"

### ISSUE THREAD

**Issue by Elfenduil** [ultrakorne/better-rolltables#11]
I created a rolltable for only generate "Currency".
It's ok but i have a warning message 

![image](https://user-images.githubusercontent.com/65708216/82728194-4e1f1c80-9cef-11ea-8f45-483ec006aefd.png)

After, i created a rolltable(master) for calling another rolltable to generate "currency".
I haven't message error but nothing is happening, no currency generate ...
 
![image](https://user-images.githubusercontent.com/65708216/82728173-321b7b00-9cef-11ea-8656-d29b4eb3974c.png)

**Comment by ultrakorne** [comment]
I will expand the currency support ( https://github.com/ultrakorne/better-rolltables/issues/1 )
to be able to add currency field directly as a text field in the roll table, this way you don't need an extra table just to do 1 currency roll.

Will probably do this in the next milestone

**Comment by sPOiDar** [comment]
So this is closed, and so is #1, but I don't understand if this is meant to work now, or how to generate currency loot by itself?
