### ISSUE TITLE
Macro Roll Results - Chat Icon Missing

### ISSUE THREAD

**Issue by Shuggaloaf** [ultrakorne/better-rolltables#111]
When using macros for roll results, chat message icons are messed up for those results. 

Chat Results:
![image](https://user-images.githubusercontent.com/79543184/126720857-249ae4b8-6e36-484d-a9db-1ee9178d8422.png)

From These Results:
![image](https://user-images.githubusercontent.com/79543184/126713498-1b280c18-7078-4592-acf2-81a634a64958.png)

**Comment by Daimakaicho** [comment]
Thanks for you feedback! This will be fixed in the next release.

**Comment by Shuggaloaf** [comment]
Much appreciated!
