### ISSUE TITLE
D&D5e Spells (SRD) Compendium has no icons!

### ISSUE THREAD

**Issue by GambetTV** [ultrakorne/better-rolltables#113]
No idea why it seems to only affect the Spells (SRD) compendium and not all the others, but when this module is enabled the Icons for the various spells vanish. Disabling this module fixes the problem!

**Comment by Daimakaicho** [comment]
I'll look it soon.

**Comment by Daimakaicho** [comment]
This will be fix when #110 is merged.

**Comment by GambetTV** [comment]
I just downloaded the update, and the issue is still present. Spells (SRD) has no icons in the compendium.

**Comment by Daimakaicho** [comment]
hum that's strange, everything works fine on my side... Do you other modules loaded too? Have you some error in brower's console?
