### ISSUE TITLE
table results labelled as text get unnecessary transformed into loot items

### ISSUE THREAD

**Issue by maxobremer** [ultrakorne/better-rolltables#114]
When a better rolltable has a text result it gets transformed into a loot item, this also removes references to items or actors within that text.
![image](https://user-images.githubusercontent.com/86924581/127035880-50f9fba6-1893-46ca-96bf-a9379499e66e.png)

**Comment by Shuggaloaf** [comment]
Second this issue. Only work-around I've found is - for all text tables anyway - change them back to a default table. Of course this does not help with mixed tables as in the screenshot in the original post. 

A fix for this would be great as long text results in Better Tables are currently unusable.

**Comment by Daimakaicho** [comment]
Thanks for your feedback! This issue will be fix in the next release. I also change font size when result is plain text:
![image](https://user-images.githubusercontent.com/1334405/127382050-0e90f947-243c-486d-ae23-c2ce52cab98d.png)
