### ISSUE TITLE
Extended Sub-Table Rolling

### ISSUE THREAD

**Issue by Aquaricat** [ultrakorne/better-rolltables#12]
Currently, you've added some support to pull one or more results from a second table, when that is the only value for that particular table line.  However, it'd be really nice to be able to do the same from a normal text line.  Consider the following example -

## Table 1 Text Line
`All creatures within 60ft of the caster are randomly teleported [[1d6]] miles to the [[1d{Table2 Reference}]].`

## Table 2 Text Lines
`north`
`south`
`east`
...

## Result
`All creatures within 60ft of the caster are randomly teleported 3 miles to the south.`

**Comment by ultrakorne** [comment]
This is interesting, I think this belong to a new type of table (so not loot tables), 
Maybe something i could call "narrative table" type or advanced text 

I would collect more use cases under a new advanced text type.

Adding support for things like this is definitely the scope of the module and will be in at some point!

**Comment by Shadoghast** [comment]
Along these lines, my hope is to use this module for my random encounters.

Mechanically, I have a master table, by terrain type and tier (e.g. Forest Lvl 1-4).  Each line on that table refers to a second table that determines the actual encounter type.

The second table can be a non-combat "story" encounter, in which case it's a block of text (or some quick notes to guide me on describing something), a trap, or a combat encounter.  If it's a combat encounter table, it's specific to a subtype (e.g. Goblinoids Lvl 1-4) that has entries along the lines of 1d4 Hobgoblins + 1 Hobgoblin Captain.  It also has a second column that selects a random "motivation" from a separate table (e.g. "hunting" or "protecting" or "resting") and a 3rd column that has a "target" (e.g. "Food" or "Treasure Pile" or "Sacred Site").

So for example, it currently flows (using paper tables atm), I roll for a random encounter.  If there is a random encounter, I roll on the master table for that terrain (Forest Lvl 1-4).  I look at the result and go to either the story, trap or combat encounter table listed.  In this example, assume the master table landed on the Goblinoids Lvl 1-4 combat encounter.  I go to THAT table and roll 3 times, once for the type of creature, once for the Motivation and once for the Target.  So let's say this time it gave me 1d4 Hobgoblins, Ambushing and Sacred Site, I know that the party is jumped by 1d4 hobgoblins who are waiting to ambush folks visiting this sacred site.

I'm hoping that at some point, this module can help me automate this, even if I have to use external tables for the Motivation and Target items.

**Comment by ultrakorne** [comment]
the original issue from Aquaricat is possible to achieve with the new story type in 1.0.0
for the encounters I will expand on the current story generators (to probably link actors). I will create a new issue for that and close this one.

From more usecases not covered by 1.0 more issues can be opened
