### ISSUE TITLE
Version Changes are not listed anywhere

### ISSUE THREAD

**Issue by Shuggaloaf** [ultrakorne/better-rolltables#125]
Anywhere I can find anyway. Is there a Changelog or version notes anywhere? 

What has changed from 1.8.1 to 1.8.2? Would be very helpful to know, especially with there being several "current" versions of FVTT out right now. 

Thanks!

**Comment by Daimakaicho** [comment]
Hello! Please have a look here : https://github.com/ultrakorne/better-rolltables/releases

**Comment by Shuggaloaf** [comment]
Maybe I'm missing it? I see notes and descriptions of changes for previous versions but not really anything for the last 2, which is what the original post was referencing. 

Sorry if I'm not seeing something obvious, fairly new to Github. This is what I see. Are there just no changelog notes for the last 2?

![image](https://user-images.githubusercontent.com/79543184/130827980-8f26db80-d21c-480e-b9ce-6c0fe56bab3f.png)

**Comment by Daimakaicho** [comment]
v1.8.1 and v1.8.2 is effectively missing, but it's only foundry's administration stuff (updating version number), nothing related to features or bugfixes. You miss nothing :)
