### ISSUE TITLE
Text Items in Loot Table do not create Loot unless price (maybe weight) is included in entry

### ISSUE THREAD

**Issue by Shuggaloaf** [ultrakorne/better-rolltables#126]
Previously Loot could be rolled to chat using the regular "roll" button with a text entity. 

It seems that now, unless "@price[xx]" is added (or I would assume possibly weight but haven't tested) that the roll only creates a text result. 

I know there were issues with text results create loot in non-loot table types, and was involved with reporting them. I'm not sure if this change was a mistake in an attempt to fix that or if this is that way you were able to get around the other issue. Preferably, when using a Loot Table ONLY, any text result will also create loot without having to add price or weight to the entry. 

**Table setup and roll results:**
![image](https://user-images.githubusercontent.com/79543184/129978097-fc82d958-c7a9-4312-8496-ad757043eaa7.png)

**Comment by Daimakaicho** [comment]
Thanks for your feedback ! This behavior is now normal as module need to find a way to know if it need to generate a new item or not. So, if there is no command into text field, your entry will be treated as plain text. To generate an item, you can set a command (@price[], @wieght[], @description[], etc).

I looked for a new way to handle generated text by adding a new entry type (next to "Text", "Entity" and "Compendium"), but unfortunately this is too much hard-coded into Foundry to allow something clean.

My last idea to handle this properly would be to a some kind of symbol at the beginning of text field to specify it's a auto-generated item, but I dislike this idea.

**Comment by Shuggaloaf** [comment]
OK that makes sense. I thought that when you fixed the issue with loot generated from text in non-loot tables, that loot tables would work the same way. But I see you're saying you couldn't differentiate by table type. Text is text no matter what kind of table so this lets you work around that. 

Easy enough to work with that. Thanks for the explanation. Actually, might want to add that to the readme in case others are expecting the same behavior. (Save you some possible issue tickets!  😉)
