### ISSUE TITLE
Better rolltable amount of specific character rolled broken

### ISSUE THREAD

**Issue by maxobremer** [ultrakorne/better-rolltables#132]
when i roll a better roll table to roll an encounter the amount of guards is a bit much here. 1d4+1 results in 180 guard privates?
![image](https://user-images.githubusercontent.com/86924581/131229750-9eb4c8fe-6743-4b5f-bb38-5ff9f09a80db.png)

**Comment by Daimakaicho** [comment]
Thanks for your feedback ! This is strange, I try to reproduce this bug on my side, and all is alright. Can you tell me what version of Better Rolltable you are using ? What are others modules activated in your campaign ? Does this happen on other tables too ?

**Comment by Daimakaicho** [comment]
Just think about it : are you using foundry v0.8.9 ? I didn't test module yet on this version.

**Comment by maxobremer** [comment]
Hi, I'm using v0.8.9 and have only had it so far with this table though haven't tested it much with others. I can send you a screenshot with my other modules later today, probably in the evening. Do you also want a screenshot with the menu when you press f12?

**Comment by Daimakaicho** [comment]
It can be helpful, thank you. If you have some errors in browser console, please attach them too. I'll try to do to an upgrade today to test Better Rolltables with v0.8.9.

**Comment by maxobremer** [comment]
first of my active modules, sorry but might be a bit much, lots are map packs from cze and peku as well as the reclusive cartographer
![image](https://user-images.githubusercontent.com/86924581/131337054-b63730bc-a2d1-48bf-80f9-071e533b17f6.png)
![image](https://user-images.githubusercontent.com/86924581/131337099-24818e60-95f2-4cbd-8896-b48008366ce4.png)
![image](https://user-images.githubusercontent.com/86924581/131337154-7a934f19-9343-4259-8cd5-95afce1abc6e.png)
![image](https://user-images.githubusercontent.com/86924581/131337189-71baa06f-e22d-4eb3-8cd9-b93865511129.png)
![image](https://user-images.githubusercontent.com/86924581/131337231-8d29a9be-acb8-43fd-9381-45c9ab979e88.png)
![image](https://user-images.githubusercontent.com/86924581/131337270-80bc663b-304a-4bd9-a703-befe3029f234.png)
![image](https://user-images.githubusercontent.com/86924581/131337312-68238fef-9075-423a-8d23-f45dd9248890.png)
![image](https://user-images.githubusercontent.com/86924581/131337350-ceecb90a-4dcf-4ca9-8f28-78b76c105512.png)
![image](https://user-images.githubusercontent.com/86924581/131337381-9ef81c11-06af-4c41-83de-55f6347a3ca5.png)

**Comment by maxobremer** [comment]
tried it again with a different table, this one has entities from compendiums and doesn't give an issue
![image](https://user-images.githubusercontent.com/86924581/131337982-39844611-10d8-4d3b-818e-ff3d4b7d640b.png)

Made a new table and issue didnt come up
![image](https://user-images.githubusercontent.com/86924581/131338512-986fd34e-096e-42b3-85ed-3cca75bf7af5.png)

**Comment by maxobremer** [comment]
recreated the table with the same entities and en with different entities, only the one with the original entities broke.
![image](https://user-images.githubusercontent.com/86924581/131339008-d4f821ee-4ab9-43e6-8be5-c6d7aee8a602.png)

also this is the f12 menu thing after rolling the table on the left:
![image](https://user-images.githubusercontent.com/86924581/131339296-832aebd9-c19f-4fb7-a322-7bf3c39cf9ff.png)

**Comment by Daimakaicho** [comment]
Your table looks to be corrupted in some way. Can you export this table and attach it here ? I will inspect it.

**Comment by maxobremer** [comment]
i couldnt upload the json to this message cause it wasnt supported so here is a we transfer link https://we.tl/t-t1s1keOi8o

**Comment by Daimakaicho** [comment]
I check your table's data and everything looks fine. I imported it into a debug world and everything works fine again. I'm pretty sure it's a conflict with another module, or some kind of corruption inside Foundry VTT about this table.

Please try the following :
 * export your table, delete it from your world then reimport it
 * create an empty world alongside your campaign with just Better Rolltables module then import your table (you don't need to import your actors to test it) 

Does this solve your issue ?

**Comment by maxobremer** [comment]
deleted it an imported it, still issues. tested it in another world with only better roll table and it worked

**Comment by Daimakaicho** [comment]
So it's a module conflict :( From your modules list and what I saw on discord theses last days, I think one of the following module is the culprit :
 * Dnd5e helpers
 * Better Rolls for 5e

Both of them had been updated recently due to 0.8.9 release.

**Comment by maxobremer** [comment]
oke, weird. I also tried to delete and recreate the npcs and that also worked. only difference is....wait i just tested it, oke so for some reason the amount of Guard Privates got multiplied by the amount of crossbow bolts the npc had

**Comment by maxobremer** [comment]
with 15 crossbow bolts 
![image](https://user-images.githubusercontent.com/86924581/131367073-ae56a326-2d43-4d80-b1a2-674f966e63f4.png)

without 15 crossbow bolts
![image](https://user-images.githubusercontent.com/86924581/131367254-1c15fb26-dce2-4950-bd57-311fccd8e9f9.png)

**Comment by maxobremer** [comment]
So I fixed it by removing any arrows and crossbow bolts and then copying the npc, putting the copies in the table and deleting the originals (just removing the ammo didnt work)
