### ISSUE TITLE
French translate

### ISSUE THREAD

**Issue by CaosFR** [ultrakorne/better-rolltables#149]
Hi,

I would like to know if they are a project for the transalate of rolls tables in french ?
If yes, I can help :).

Thanks

**Comment by DanielBoettner** [comment]
The french translations are here:

https://github.com/ultrakorne/better-rolltables/blob/master/lang/fr.json

This should work if you use FoundryVTT in french.

The "main"/fallback file is to be found here:
https://github.com/ultrakorne/better-rolltables/blob/master/lang/en.json

You can check for differences and add missing translations. Or suggest better translations.

Easiest way to contribute is to fork the repo. And create PRs with the changes/improvments.

**Comment by CaosFR** [comment]
Can you tell me what is the formating for your /pack/*.db files.
I try to parse it with .db file editor but it's not work (not a database).
