### ISSUE TITLE
When generating loot it only rolls once on the table regardless of the amount of rolls formula

### ISSUE THREAD

**Issue by Avitale34** [ultrakorne/better-rolltables#16]
As title states, when generating loot it only rolls once on the table regardless of the amount of rolls formula.

**Comment by ultrakorne** [comment]
It's working with a few tables I have tested. 
Can you post me a screenshot of your table setup and check that there are no errors in console?

**Comment by ultrakorne** [comment]
when you add a formula you have to click "update" before rolling to save the data to the table. Maybe was that?

**Comment by ultrakorne** [comment]
if this is still happening please reopen a new issue with more info
