### ISSUE TITLE
Pull loot under a certain value

### ISSUE THREAD

**Issue by Bouvi** [ultrakorne/better-rolltables#40]
For example, I have the roll table only pull loot valued at 50gp and under.  This keeps my level 1s from getting uber loot.

**Comment by ultrakorne** [comment]
I think this can be achieved by having different tables based on group level, would be too specific for an implementation that is generic enough.

In the example treasure loot tables by CR included with the module I use a master table where the "roll formula" is the CR level, used as an index to roll on the appropriate table by cr rating
