### ISSUE TITLE
Generate loot from rollable tables in a compendium

### ISSUE THREAD

**Issue by MSAbaddon** [ultrakorne/better-rolltables#45]
The Pathfinder 2 system provides rollable tables for all the available equipment (e.g. 11th-level permanent items). Currently it is not possible to use such a table directly from the compendium to generate loot - they need to be copied to the world's rollable tables first.

**Comment by ultrakorne** [comment]
have you checked this?
https://github.com/ultrakorne/better-rolltables/wiki/API-for-macros-and-modules#how-to-generate-tables-from-compendia

you can use a macro to generate loot tables from compendia

**Comment by MSAbaddon** [comment]
Jeah, checked this and it's a great function.
Doesn't exactly help me though. The Pathfinder 2 system already has various rollable tables (one table for each level, both for permanent and consumable items) in a rollable tables compendium. It would be great if I could just insert such a rollable table to a loot table as I do with compendium entries for items.
As it is now I have to drag the rollable table from the compendium to the rollable tables of my world first.

**Comment by ultrakorne** [comment]
If i understood correctly, you can add the name of the compendium in brackets, before the table name to reference tables that are not in the world like this:

![image](https://user-images.githubusercontent.com/2083769/85988188-f90daf00-b9ee-11ea-8791-f05179151c35.png)

**Comment by MSAbaddon** [comment]
Works perfectly, thanks for the info - missed that function :-)
