### ISSUE TITLE
Takes 30s to a minute for tables to update

### ISSUE THREAD

**Issue by DiDeoxy** [ultrakorne/better-rolltables#47]
I can add things from a compendium no problem but to save the table with update takes 30s to a minute. 

Using foundry on Raspbian on a pi 4 with 4GB ram.

Could it be a write speed issue on my SD card?

I look at the console output and it takes 30s to a minute for preUpdateRollTable to appear then the next steps go very fast.

So something is holding it up but I don't know what, could it be better-rolltables?

**Comment by ultrakorne** [comment]
do you have performance issue without the mod? how big is the table?

in preUpdateRollTable i do very little. 
The majority of the things happen when you open the rolltable view, the preUpdateRollTable call is mostly default foundry stuff and I just store 3 extra values for the mod.

**Comment by DiDeoxy** [comment]
I do have performance issues without the mod the mod might make them worse, not sure. It gets worse as the table grows in size. I started a new world with no tables or mods and the issue persists. It's very frustrating. Making tables is practically impossible.

**Comment by DiDeoxy** [comment]
I tried it on my desktop (transferred the world, new install of foundry) and the issue persists, though not as extreme.

**Comment by ultrakorne** [comment]
you should ask in the foundry discord about the issue, it's probably related to foundry itself if the mod is off. I can't help you much with this

**Comment by DiDeoxy** [comment]
Hey, I figured it out, its because I was rolling on compendium entries.
