### ISSUE TITLE
Bug - Error on the javascript when i click a rolltable 

### ISSUE THREAD

**Issue by p4535992** [ultrakorne/better-rolltables#49]
**Environment Details**

Foundry VTT Version: 0.7.0
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.94
Modules Enabled?: Yes
Version used of the module: 1.5.0

**Description of the issue:**

There is a javasript exception when i open the classic " FVTT Community Tables - 5E" rolltable  from the "Compendium Packs" .
The error make the buttons on the bottom not clickable.
Here a screenshot of the error

![bug](https://i.imgur.com/38OlPzj.jpg)

Sorry for the poor technical details.

**Comment by ultrakorne** [comment]
will look into it!
0.7 changed some of the stuff in rolltable so the module will need an update for 0.7

**Comment by ultrakorne** [comment]
@p4535992 i pushed an update for foundry 0.7 in version 1.6.1 of the brt module, this should fix this error.
