### ISSUE TITLE
Tables based on percent chance.

### ISSUE THREAD

**Issue by Magma2222** [ultrakorne/better-rolltables#51]
It would be great if we could use Roll Tables for percentage based loot tables. For example 

Item A - 30%
Item B - 60%
Item C - 25%

So when the table is rolled each item has an independent chance to be drawn. You could obtain 0 - 3 items but no duplicates.

**Comment by ultrakorne** [comment]
you can use overlapping ranges to achieve that. 
I don't want to change the way foundry tables are used, so they are compatible as much as possible with the default ones.

**Comment by Magma2222** [comment]
Perhaps it's because I'm new to Foundry but I'm not sure I can.

With overlapping ranges some results wouldn't be possible.

For example in the below image there is no way to obtain 0 items and no way to obtain both item A and C.

![image](https://user-images.githubusercontent.com/7110215/91305177-39867080-e785-11ea-946e-8521b1f21d6c.png)

**Comment by ultrakorne** [comment]
you can have 1-30 and 1-90 for example to have both item being drawn when rolling under 30

**Comment by Magma2222** [comment]
That still wouldn't result in what I am looking for. In that instance if Item A is obtained Item B would always be included. Additionally Item B would have a 90% chance instead of a 60%.

These kind of treasure tables are common for older RPGs like B/X D&D.

Say a monster is supposed to have a treasure table like this.

Item A - 30%
Item B - 60%
Item C - 25%

When the table is rolled each item has an independent chance of appearing. At the table I would do the following.
I would roll a 1d100 for Item A, if it is 1 - 30 they would get that item otherwise nothing. I would then repeat for Item B and C.

This would result in the possibility of obtaining any combination of A, B and or C, or potentially nothing at all.

**Comment by neffers-gridcoin** [comment]
You could try a set of nested tables where the first table calls all 3 'Item Tables'

![image](https://user-images.githubusercontent.com/12642131/93439734-d0e36d00-f8c6-11ea-8d57-b96f9d60650d.png)

I've made a quick example. You only need to press roll on the 'A Monster's Loot' table and it will trigger a roll on each of the Item tables then output it to chat.
