### ISSUE TITLE
Better Roll Tables not working

### ISSUE THREAD

**Issue by Alexis-Grimm** [ultrakorne/better-rolltables#58]
I've just recently updated to 0.7.5, and am having an issue where the better table just can't roll either from a macro or from the table itself. I have also realized that this has been true since before I even updated to 0.7.x I get this error in the console when trying to roll from it
`Uncaught (in promise) TypeError: (new DicePool(...)).roll is not a function
    drawMany http://18.222.170.160:30000/modules/better-rolltables/scripts/core/brt-api-changes.js:22
    rollManyOnTable http://18.222.170.160:30000/modules/better-rolltables/scripts/core/brt-builder.js:52
    betterRoll http://18.222.170.160:30000/modules/better-rolltables/scripts/core/brt-builder.js:15
    betterTableRoll http://18.222.170.160:30000/modules/better-rolltables/scripts/better-tables.js:49
    onclick http://18.222.170.160:30000/modules/better-rolltables/scripts/better-table-view.js:79
    enhanceRollTableView http://18.222.170.160:30000/modules/better-rolltables/scripts/better-table-view.js:79
    _call http://18.222.170.160:30000/scripts/foundry.js:2426
    call http://18.222.170.160:30000/scripts/foundry.js:2411
    callOriginalFunction http://18.222.170.160:30000/modules/furnace/Patches/Patches.js:57
    <anonymous> http://18.222.170.160:30000/modules/furnace/QoL/Debug.js:42
    _render http://18.222.170.160:30000/scripts/foundry.js:4472
    _render http://18.222.170.160:30000/scripts/foundry.js:5088
    render http://18.222.170.160:30000/scripts/foundry.js:4404
    render http://18.222.170.160:30000/scripts/foundry.js:5553
    render http://18.222.170.160:30000/scripts/foundry.js:28692
    _onUpdate http://18.222.170.160:30000/scripts/foundry.js:29251
    entities http://18.222.170.160:30000/scripts/foundry.js:29229
    _handleUpdate http://18.222.170.160:30000/scripts/foundry.js:29222
    update http://18.222.170.160:30000/scripts/foundry.js:29203
    update http://18.222.170.160:30000/scripts/foundry.js:29278
    normalize http://18.222.170.160:30000/scripts/foundry.js:34133
    _onNormalizeResults http://18.222.170.160:30000/scripts/foundry.js:18603
    jQuery 2
brt-api-changes.js:22:38
    onclick http://18.222.170.160:30000/modules/better-rolltables/scripts/better-table-view.js:79
    AsyncFunctionThrow self-hosted:678
    (Async: async)
    enhanceRollTableView http://18.222.170.160:30000/modules/better-rolltables/scripts/better-table-view.js:79
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674
    (Async: async)
    _call http://18.222.170.160:30000/scripts/foundry.js:2426
    call http://18.222.170.160:30000/scripts/foundry.js:2411
    callOriginalFunction http://18.222.170.160:30000/modules/furnace/Patches/Patches.js:57
    <anonymous> http://18.222.170.160:30000/modules/furnace/QoL/Debug.js:42
    _render http://18.222.170.160:30000/scripts/foundry.js:4472
    AsyncFunctionNext self-hosted:674
    (Async: async)
    _render http://18.222.170.160:30000/scripts/foundry.js:5088
    render http://18.222.170.160:30000/scripts/foundry.js:4404
    render http://18.222.170.160:30000/scripts/foundry.js:5553
    render http://18.222.170.160:30000/scripts/foundry.js:28692
    _onUpdate http://18.222.170.160:30000/scripts/foundry.js:29251
    entities http://18.222.170.160:30000/scripts/foundry.js:29229
    map self-hosted:221
    _handleUpdate http://18.222.170.160:30000/scripts/foundry.js:29222
    update http://18.222.170.160:30000/scripts/foundry.js:29203
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674
    (Async: async)
    update http://18.222.170.160:30000/scripts/foundry.js:29278
    normalize http://18.222.170.160:30000/scripts/foundry.js:34133
    _onNormalizeResults http://18.222.170.160:30000/scripts/foundry.js:18603
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674
    (Async: async)
    _onNormalizeResults self-hosted:1161
    jQuery 2
`

**Comment by MadMerick** [comment]
I have this problem with the new release too

**Comment by ultrakorne** [comment]
do you have 1.6.2?
the auto update does not work, i will have to fix it but if you manually install 1.6.2 it should work.
can you try to install https://raw.githubusercontent.com/ultrakorne/better-rolltables/master/module.json  
(or uninstall and reinstall it again from the modules view)

**Comment by MadMerick** [comment]
> do you have 1.6.2?
> the auto update does not work, i will have to fix it but if you manually install 1.6.2 it should work.
> can you try to install https://raw.githubusercontent.com/ultrakorne/better-rolltables/master/module.json
> (or uninstall and reinstall it again from the modules view)

That worked! Thanks!

**Comment by Alexis-Grimm** [comment]
Ah yeah that worked, sorry about that I normally think to check that when I have module issues
