### ISSUE TITLE
Support for applying generated loot directly to selected tokens

### ISSUE THREAD

**Issue by VaderDojo** [ultrakorne/better-rolltables#61]
Greetings!

I found that for random encounters and other generated events within adventures that specify their own loot tables by zone (instead of using standard CR-based tables), fell within a scenario not well covered by applying pre-generated loot to a static prototype actor, nor to generating a separate "New Loot" actor, nor enhancing the module to work off of the monster CR linked to the standard treasure tables.  Solving for this also helped randomize the loot between tokens instead of identical loot for all tokens created from a single prototype actor which my players felt broke immersion.

To cover this scenario, I created two new methods within the LootCreator object  ( addCurrenciesToTokens() and addItemsToTokens() ).  These are used to iterate through a group of n-number of selected tokens, verify that they have complete currency properties set, and add the generated additional currency and loot to the tokens (rolled individually).

With the addition of these methods I have been able to quickly apply token-unique and scenario specific loot tables to a large group of tokens with a single button press.  I am considering adding a second use-case where the loot table is generated off of the monster CR via the standard tables, but only applied to tokens when I specify instead of on initial drag onto the canvas.

Code can be shared, committed, or put into a sister project depending on how the project owner desires to govern the new functionality.

**Comment by ultrakorne** [comment]
its quite interesting, i had in my todo list to create something like you described but didnt had the time to work on the module beside general bug fixes lately.

how much code is it? do you have it already somewhere in a fork?

**Comment by VaderDojo** [comment]
It is very little code.  Just two small methods and a small tweak to the orchestration logic and UI.  Fork can be found here: https://github.com/VaderDojo/better-rolltables

In my fork I commented out the Actor driven logic and replaced it with my Token-driven logic.  In a public module I would put the last bit of polish to add a UI toggle to select Actor or Token logic and also improve UI feedback for when the generated loot has completed.  Currently the generation is silent which may cause users to click "Generate Loot" multiple times.

**Comment by VaderDojo** [comment]
I noticed a versioning error where I committed a dev branch to master that has a defect relating to iterating through the selected tokens in the addCurrency and addItems methods instead of iterating within the generateLoot orchestration with fresh result values for each token.

The correct version has been committed to my fork's master branch.

**Comment by ultrakorne** [comment]
I see. Many user are actually an actor not a token to hold the generated loot but I find your approach could also be an interesting use case. 

I would like to add it as an option and not as a functionality replacement.
I might included it first just as an additional macro/api

**Comment by VaderDojo** [comment]
For sure.  I think actor is the way to go for singular unique loot/equipment that can appear between many scenes.  Having it as a separate macro makes sense and what I was thinking of when I mentioned having a toggle between Actor or Token application of loot.

As to why I felt there was a gap in functionality... It is because for the cannon-fodder types I prefer to keep the Actor tab clean by pulling from a compendium and then storing the instance of that creature's loot within the token and not add more maintenance tasks of cleaning up n-number of identical generic goblin and orc Actors.

Hope you/others find it useful too.

Thanks for the base functionality of the mod.  It's been a great enhancement to the tool kit.

**Comment by ultrakorne** [comment]
1.6.4 is release containing your code. thx!
