### ISSUE TITLE
Loot table rolling appears to be broken

### ISSUE THREAD

**Issue by Pyroman2xxx** [ultrakorne/better-rolltables#64]
I can roll when the table type is set to 'Default Table' but 'Loot Table' does nothing when I click either 'Generate Loot' or 'Roll'.
Did the recent base update cause this to stop working? I have not used a loot table in some time so I can't tell when this started.
Updated to 0.7.9 FVTT and 1.2.0 DnD5e.

**Comment by daredyoshi** [comment]
It seems like all of the better tables are broken in newer versions of foundry, I first noticed it with 0.7.8 FVTT. Looking into the consol there's the following error
```
foundry.js:8339 The Roll.minimize(formula) function is deprecated in favor of Roll#evaluate({minimize: true})
minimize @ foundry.js:8339
foundry.js:8350 The Roll.maximize(formula) function is deprecated in favor of Roll#evaluate({maximize: true})
maximize @ foundry.js:8350
brt-api-changes.js:22 Uncaught (in promise) TypeError: (intermediate value).roll is not a function
    at RollTable.drawMany (brt-api-changes.js:22)
    at BRTBuilder.rollManyOnTable (brt-builder.js:52)
    at BRTBuilder.betterRoll (brt-builder.js:15)
    at BetterTables.betterTableRoll (better-tables.js:49)
    at HTMLButtonElement.newRollButton.onclick (better-table-view.js:79)
```

**Comment by ultrakorne** [comment]
did you try to uninstall and reinstall the mod? you are probably using an old version and there was an issue with the auto update of the module some months back.

Uninstalling and reinstalling should fix it

**Comment by Pyroman2xxx** [comment]
Thank you. Uninstalling and reinstalling did fix it.
