### ISSUE TITLE
Feature Request: Groups

### ISSUE THREAD

**Issue by geoidesic** [ultrakorne/better-rolltables#67]
Would be handy to have a groups field in the table. Then you can group items together as a single roll result with multiple items in the group to be shown in chat. 

This is handy e.g. for creating a mixed encounter, like 1d4 Orcs + an Orc Captain

**Comment by ultrakorne** [comment]
it can be done by having the overlapping ranges
have 2 table rows where the they both have for example 1-2 as range, when a 1 is rolled, both results are selected.

It is the foundryVTT way of doing this, I prefer to keep it the way it is done in vanilla foundry when the feature is already present.
