### ISSUE TITLE
 Incorrect number of object draws

### ISSUE THREAD

**Issue by Elfenduil** [ultrakorne/better-rolltables#7]
Hi,

I created a tool table, when i click on Generate Loot, i have only one item to create in my Actor "Aubergiste" but my formulas indicate 1d4 + 4 or 1d6 + 6?

Thank you

![Tirage incorrecte](https://user-images.githubusercontent.com/65708216/82549437-39128400-9b5d-11ea-8b90-01921edc4cee.PNG)

**Comment by ultrakorne** [comment]
adding text with formulas is not supported anymore (instead of `1d6+6 of [table]` the correct formula is just `1d6+6 [table]`
