### ISSUE TITLE
Cannot copy chat results from Story Tables

### ISSUE THREAD

**Issue by dangerdaren** [ultrakorne/better-rolltables#71]
Fantastic module! One issue: when rolling a Story Table, the results in the chat window cannot be copied. I made a really awesome adventure generator, but I found I can't copy the resulting text to paste in my campaign prep notes. Is there anything that can be done to allow copying the resulting text?

**Comment by DanielBoettner** [comment]
Confirmed.

Caused by FoundryVTT's css preventing text selection in general and only allowing it in certain spots.
We'll have to think about a solution.

Quickfix for you would be adding some css to you system 

```css
.chat-message .message-content p {
    user-select: text;
}
```

**Comment by DanielBoettner** [comment]
PR exists.

The generated story text will be selectable in the future. 
But has to be copied to the clipboard via a keyboard shortcut (`cmd + c`).
