### ISSUE TITLE
Macro Blind GM rolls

### ISSUE THREAD

**Issue by dangerdaren** [ultrakorne/better-rolltables#72]
When making a macro to roll on a better table, I'm having a hard time getting the rolltables to be made as anything but public. I'd like the macro to roll it as a Blind GM roll, but the standard syntax doesn't seem to work.

**Comment by DanielBoettner** [comment]
Could you please provide an example macro?
Would help to know what to test against.

**Comment by dxwarlock** [comment]
I came to ask the same thing. I cannot find any API documentation on how to send results to chat as a GMroll.

Using the example in the API, there is no where to add a version of {rollMode:"gmroll"}

`const table = game.tables.getName("Master Loot Rolls");
game.betterTables.betterTableRoll(table);`

**Comment by DanielBoettner** [comment]
This will be possible with #142 

The macro would look like this:

```javascript

const table = game.tables.getName("Master Loot Rolls");

//blind roll
game.betterTables.betterTableRoll(table, {rollMode: 'blindroll'});

//gm roll
game.betterTables.betterTableRoll(table, {rollMode: 'gmroll'});

//self roll
game.betterTables.betterTableRoll(table, {rollMode: 'selfroll'});
```

Only these values are valid. Anything else is ignored.
