### ISSUE TITLE
Does not work in Foundry 0.8.x

### ISSUE THREAD

**Issue by ravingdragoon** [ultrakorne/better-rolltables#73]
The Better Rolltable interface does not come up when creating a rollable table in Foundry 0.8.x

**Comment by Wade0004** [comment]
I need my tables to roll into actors!  I've gotten so dependent on being able to roll a "store" at a moments notice!  PLEASE

**Comment by CarnivorousM** [comment]
As Wade stated: I have the entire DMG Loot tables built and crosslinked depending on BetterTables and LootSheet5e for populating actors when I get the inevitable "I loot the bodies".
Now - it doesn't even show the option for being a Loot Table nor the Add Loot to Actor :(

**Comment by ultrakorne** [comment]
I v been inactive in foundry lately, I will check as soon as I have time if the fix is easy to do (hopefully)
would be great to find someone that I can add to the repo to help updating / fixing the module when there are breaking changes.

Please let me know if you know someone or someone is interested

**Comment by PawLoh23** [comment]
Thanks for an amazing module @ultrakorne. Waiting patiently for this to fix prior to updating to the new version of Foundry.

**Comment by jfvandyk** [comment]
Hi @ultrakorne,

I've been having a look at this issue, whilst I'm fairly new at FoundryVTT modules, so I could be wrong, however by the looks of your code, you are finding the RollTable via an the ID of an element, that should be something like app-61, but it's some random value such as "-rAfig4LdCihzojci", so I suspect this might actually be a bug in FoundryVTT, then a problem with the module.

File: better-table-view.js line 11, is where I think it is failing.

**Comment by ultrakorne** [comment]
I m in the process of making a release, the issue was that foundry 1.8 changed the way to id views using a custom attribute "data-appid" instead of the field id.
My fix seems to work but i didnt test much at all, let me know when 1.6.5 is up if everything is fine

**Comment by RustyXXL** [comment]
I'm trying around with the loot tables, and while they now show up, nothing seems to really work.
When trying to edit them and then clicking on update they switch to default tables, when trying to use an old one I already had nothing happened when trying to roll normal and when trying to generate a loot actor I got a message "Reguired field "name" not found in itemData".
The datastructures got a massive overhaul in 0.8.x, so I assume this is related to that. I think the default Rolltables also changed in 0.8.x, but I'm not to sure about that.

As a sidenote: I linked this issue on the leage Discord I send you in my dm on Discord, regarding your search for someone helping you. Maybe you want to get in contact with the folk there yourself. :)

**Comment by ultrakorne** [comment]
will have a look after dinner... seems more stuff changed. 
I was a bit too quick to release after fixing 1 issue

**Comment by ultrakorne** [comment]
new version 1.6.6 is up. I tested very quickly will check again tomorrow if there are more issues

**Comment by PawLoh23** [comment]
I get the following error when trying a story table (e.g. Random NPC) "Only Journal entries are supported in the story generation as table results"

**Comment by cbgh2021** [comment]
![image](https://user-images.githubusercontent.com/83421141/121908228-c1b32200-cd67-11eb-96cd-953839bec469.png)

updated but still not seeing an option to pick better roll table

**Comment by cbgh2021** [comment]
Ignore that, disabling npc loot sheet then re-enabling it seemed to fix everything.

**Comment by cbgh2021** [comment]
clicking update table causes the table to switch back to the default table for me, anyone else?
Also embedding tables no longer seems to work.
When I roll a table that has tables inside,  it does this

**Comment by cbgh2021** [comment]
![image](https://user-images.githubusercontent.com/83421141/121910917-3c7d3c80-cd6a-11eb-9845-f1facab1b2ef.png)

**Comment by Wade0004** [comment]
I was about to bring up the same thing.  I have tables that will roll
tables that will roll tables, and I'm getting this error:

Required field "type" not present in ItemData

That error only comes when I'm rolling a "loot table" that references
another table that is in a compendium. and I get the same result as
@cbgh2021 when i roll a "better table" that references a compendium table.

I'm going to build a small table with all new links to items/compendiums
and report whether that works or not.
[image: image.png]
[image: image.png]

**Comment by Wade0004** [comment]
So, no errors with fresh links, but it still doesn't roll the subsequent
table, it just added it to the loot actor:

[image: image.png]

**Comment by ultrakorne** [comment]
Quick update:

* pushing v1.6.7 that should fix the inner roll tables (0.8 massively changed data structure and I need to hunt and fix one by one the places when this occurs based on those reports)
* I am looking for someone to help maintain and take over the dev of the module
* The table loosing the "type" when clicking update, I spent a few hours on this issue, and there is something funky going on and "seems" a bug on foundry but I couldnt find a workaround.

**Comment by RustyXXL** [comment]
> 
> 
> Quick update:
> 
>     * I am looking for someone to help maintain and take over the dev of the module

You are probably best of looking on either the Foundry Discord or on the League of Extraordinary Foundry VTT Developers Discord: https://discord.gg/a8cBRDsK
I imagine there are more potential Devs who might see that.

**Comment by Wade0004** [comment]
Hi,

When my table rolls multiple results they no longer show up as a "stacked"
multiple item, but instead as several single items:

[image: image.png]

I truly wish i knew more about Development or how to take over/help, but i
don't. So instead I'll send you more money and beg!

**Comment by ultrakorne** [comment]
screenshot doesnt show, can you send the screenshot in discord @ ultrakorne ?

Is the module usable in the current state? i wanted to just get it working decently and fix the rest later.

**Comment by lizShack** [comment]
(So sorry to add another issue to the pile)
I'm seeing an issue where whenever the table is saved, the Better Table Type is returning to default.

![Table Types don't save](https://user-images.githubusercontent.com/7528068/122285260-1cf22b00-ceb4-11eb-9670-a8f4aecff9d7.gif)

**Comment by ultrakorne** [comment]
gonna close this issue and there are separate issues for every bug in 0.8x.
let's keep it 1 issue to be 1 bug
