### ISSUE TITLE
betterTables.createTableFromCompendium does work

### ISSUE THREAD

**Issue by rinnocenti** [ultrakorne/better-rolltables#77]
Self-explanatory, the api to generate tables is not working in v.8.x

**Comment by DanielBoettner** [comment]
@rinnocenti if you wish you can test this [branch](https://github.com/DanielBoettner/better-rolltables/tree/ScrollsFix).
The PR #86 will hopefully get these changes into the next release.

The method is working now again and I added an option to the context menu of a compendium to start the generation.
The generation via macro should also still work (didn't test this yet).

![image](https://user-images.githubusercontent.com/21986545/123963654-f9020f80-d9b2-11eb-8f37-68225b0a55f3.png)

![image](https://user-images.githubusercontent.com/21986545/123963603-ec7db700-d9b2-11eb-818d-d6e03bc27b4d.png)
