### ISSUE TITLE
nested tables do not work with better tables.

### ISSUE THREAD

**Issue by ultrakorne** [ultrakorne/better-rolltables#78]
nested tables do not work with better tables.
does not count the number of items in the improved table. (Update revert in normal table)

![image](https://user-images.githubusercontent.com/3178127/122238137-4734f000-ce96-11eb-86be-a9391c6df86d.png)

_Originally posted by @rinnocenti in https://github.com/ultrakorne/better-rolltables/issues/76#issuecomment-862432035_

**Comment by DanielBoettner** [comment]
Is that an issue directly with better rolltables or could code this help 
handle that?

Thats what I use in **lootpopulatornpc5e** to handle getting tables instead of items.

```js
    static async _rollSubTables(item, index = 0) {
		if (item instanceof RollTable) {
			let subTableResults = await item.roll();

			if (subTableResults.results[index].data.collection === "Item") {
				item = game.items.get(subTableResults.results[index].data.resultId);
			} else {
				let itemCollection = game.packs.get(subTableResults.results[index].data.collection);
				item = await itemCollection.getDocument(subTableResults.results[index].data.resultId);
			}

			if (item instanceof RollTable) {
				item = await this._rollSubTables(item, index);
			}
		}

		return item;
	}
```

**Comment by ultrakorne** [comment]
screenshot above is setup incorrectly since the table called "treasure tser pool" has to be set to better table like in the screenshot below

![image](https://user-images.githubusercontent.com/2083769/123004031-5e06a580-d3b4-11eb-8faa-1486aa48b489.png)

the amount of times the sub table has to be rolled needs to be added in the formula field in the table result (in the example above, 1d6 times rolls on the nested table)

There is a bug that the formula in the result was not shown and will be fixed in upcoming version
