### ISSUE TITLE
Roll table not assigning currency in loot sheet when using 'generate loot'

### ISSUE THREAD

**Issue by kuchrk24** [ultrakorne/better-rolltables#79]
Foundry 0.8.7
Better Roll Tables 1.6.8
![Screenshot 2021-06-23 223643](https://user-images.githubusercontent.com/74018852/123194002-bbadf700-d473-11eb-8097-53b4c9c57501.png)

**Comment by DanielBoettner** [comment]
Just telling from you screenshot, you do not have entered a formula for currency generation.

**Comment by ultrakorne** [comment]
@DanielBoettner when the table is rolled the text like 5d6[cp] should be parsed, so it looks like a bug

**Comment by kuchrk24** [comment]
This roll table worked before the 0.8.x updates.

**Comment by ultrakorne** [comment]
should be fixed in 1.6.10

**Comment by kuchrk24** [comment]
Yup looks like it works now. Thanks!
