### ISSUE TITLE
Broken Inline Rolls on Loot Table

### ISSUE THREAD

**Issue by Shuggaloaf** [ultrakorne/better-rolltables#84]
Using an inline roll in a text entity of a loot table no longer works. It is failing in multiple ways:
1. It breaks the text apart at the inline roll. Anything that comes after that inline roll is no longer a part of the item; and
2. It throw an error saying "no table named <inline roll formula> found in compendium.

Using a book with "volumes" as an example, previously it would have displayed like this (with everything within the brackets part of the item name) {Some Book Vol. <roll result>: Additional Text}. 

Now it looks like this:
<img src="https://user-images.githubusercontent.com/79543184/123549456-20e53f00-d737-11eb-92d3-3a1c928825a4.png" width="35%"/>

Here is the table and the error about compendiums:
<img src = "https://user-images.githubusercontent.com/79543184/123549467-30fd1e80-d737-11eb-8bd7-fddb3aafebdd.png" width = "50%"/>

**Comment by DanielBoettner** [comment]
Can confirm this.

It doesn't occur every time and is maybe related to when and how results come in.

**Comment by DanielBoettner** [comment]
I think I have a fix for that:
![image](https://user-images.githubusercontent.com/21986545/123625261-e0a5bf80-d80f-11eb-949c-442e29055dd6.png)

Will have to check with @ultrakorne and likely publish this with other fixes.

**Comment by Shuggaloaf** [comment]
Great! Thanks for the update and possible fix @DanielBoettner

**Comment by DanielBoettner** [comment]
Were you able to test the newest release?

**Comment by Shuggaloaf** [comment]
Hey @DanielBoettner so just to let you know - the table type not changing is definitely fixed. Unfortunately my issue persists. Still breaking apart the "item" after the inline roll and still throwing the "no table named {whatever inline roll is} in compendium". See below.

<img src= "https://user-images.githubusercontent.com/79543184/123823977-a568c680-d8cb-11eb-9f57-20a74a4dc7ec.png" width="50%"/>

**Comment by DanielBoettner** [comment]
For some reason the fix isn't in the master branch.

I will recreate that and push it to another branch for the next release.

**Comment by DanielBoettner** [comment]
you can test this branch if you like: https://github.com/DanielBoettner/better-rolltables/tree/ScrollsFix

**Comment by Shuggaloaf** [comment]
Tested it out and it works perfectly. Thanks for fixing that!
