### ISSUE TITLE
createTableFromCompendium can't find compendiums

### ISSUE THREAD

**Issue by anjenpai** [ultrakorne/better-rolltables#89]
Issue: when using a macro to make a roll table from a compendium OR when right-clicking on a compendium and pressing generate a roll table, a popup announces that the respective compendium was not found. The real issue appears to be that the compendiums are not indexed (see workaround below)
I disabled modules to rule out conflicts. Problem occurs even with dnd5e.items. Tested only with item type compendiums.

Workaround: open the wanted compendium -> open 1 item (when looking in console this triggers the indexing of the compendium) -> use macro / Rclick generate roll table -> Enjoy

Thanks for the great module <3

**Comment by DanielBoettner** [comment]
Will check that.
