### ISSUE TITLE
Incorrect Loot table output to Chat when roll fall on two lines with same range

### ISSUE THREAD

**Issue by Daimakaicho** [ultrakorne/better-rolltables#90]
Hello. I'm implementing DMG's random treasures using Better Rolltables (latest version) and I met the following issue.
When I create un Loot table with lines sharing the same range, output to chat is messed up (result is always the same):
![image](https://user-images.githubusercontent.com/1334405/124797037-1c4c3200-df52-11eb-9583-cc335a5932fb.png)
Expected values are (using default table):
![image](https://user-images.githubusercontent.com/1334405/124797730-e491ba00-df52-11eb-98f7-1a9ff4eb1a95.png)

So item count in card is right (here we should have 2 items in all case), but items are "merged" into the first one. Please note this work fine with all other table type and when I generate loot to actor.

I dig into code a little, and issue seems to be around `LootChatCard.addToItemData()` where existing item check is messed up. After first item is added to `itemsData` on the first loop, all next checks are wrong. I notice `this.itemsData.map(i=>i.item.id)` always return `[undefined]` in this case. For now, I just replaced first line of `LootChatCard.addToItemData()` method like this:
```javascript
const existingItem = this.itemsData.find(i => i.item._id === itemEntity._id)
```
This seems to work pretty well, but I don't know if this fix is okay.

EDIT: working on a PR for this one.

**Comment by Daimakaicho** [comment]
I made a PR to fix this ussie and a some other issues I notice on chat card when rolling loot table: #91

**Comment by ultrakorne** [comment]
@Daimakaicho thank a lot for the PR, i m preparing a new build with your code in as well
