### ISSUE TITLE
TypeError: Cannot set property _id of [object Object] which has only a getter

### ISSUE THREAD

**Issue by Steuls** [ultrakorne/better-rolltables#95]
When pushing the Generate Loot button on a Loot Table such as the Item table given in the compendium with the module, the TypeError: Cannot set property _id of [object Object] which has only a getter error occurs for each item that it tried to add and leaves the LootSheetNPC empty. This error does not occur for some items such as scrolls and some other items such as Agate and Herb. Screenshot below. Foundry Version 0.8.8.
![image](https://user-images.githubusercontent.com/45470638/125316116-b5eb5900-e32f-11eb-900a-86839576c6b0.png)

**Comment by Daimakaicho** [comment]
Same issue as #89, I submit a PR to fix it (#93)
