### ISSUE TITLE
Failed to generate Roll Table from Compendium, "Compendium Named [...] not found."

### ISSUE THREAD

**Issue by MatthewDF** [ultrakorne/better-rolltables#98]
![image](https://user-images.githubusercontent.com/38047891/125630241-32cbbfaf-9812-44dd-83a5-ad1e38419f1d.png)

Hello. The above error occurs when trying to generate a roll table from any compendium.

Versions:
Foundry - 0.8.8
PF1 - 0.78.15

With only BRT active.

**Comment by Daimakaicho** [comment]
Same issue as #89 and #95, this will be fixed in next release.
